services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: vulp-postgres
    environment:
      POSTGRES_USER: vulp
      POSTGRES_PASSWORD: vulp
      POSTGRES_DB: vulpdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: vulp-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
